variaveis_explicadas = {
    "fps_1": """Quadros por segundo (1-30)""",
    "gop_1": """Intervalo de quadros-chave/GOP (2-150 frames)""",
    "brmode_1": """Modo de controle de taxa (0=CBR, 1=VBR)""",
    "imagegrade_1": """Qualidade de imagem (1-6, 1=melhor qualidade)""",
    "width_2": """Largura do vídeo em pixels (fluxo secundário)""",
    "height_2": """Altura do vídeo em pixels (fluxo secundário)""",
    "bps_2": """Taxa de bits em kbps (32-2048 para fluxo secundário)""",
    "fps_2": """Quadros por segundo (1-30)""",
    "gop_2": """Intervalo de quadros-chave/GOP (2-150 frames)""",
    "brmode_2": """Modo de controle de taxa (0=CBR, 1=VBR)""",
    "imagegrade_2": """Qualidade de imagem (1-6, 1=melhor qualidade)""",
    "audioflag": """Status do áudio (0=desligado, 1=ligado)""",
    "httpport": """Porta HTTP. Valores: 80 ou 1024-49151""",
    "lancode": """Código de idioma (0=Chinês, 1=Inglês, 2=Francês, 3=Alemão, 4=Italiano, 5=Espanhol, 6=Russo, 8=Coreano, 9=Polonês)""",
    "pandir": """Direção horizontal (0=normal, 1=invertida)""",
    "tiltdir": """Direção vertical (0=normal, 1=invertida)""",
    "panspeed": """Velocidade do movimento horizontal (0=rápido, 1=médio, 2=lento)""",
    "tiltspeed": """Velocidade do movimento vertical (0=rápido, 1=médio, 2=lento)""",
    "panscan": """Ativa/desativa varredura horizontal automática (0=desligado, 1=ligado)""",
    "tiltscan": """Número de ciclos de varredura vertical (1-50, 0=desativado)""",
    "movehome": """Centraliza a câmera na posição inicial ao reiniciar (on/off)""",
    "movesteptimeout": """Tempo máximo (ms) para movimentos passo a passo""",
    "presettimeout": """Tempo máximo (s) para alcançar posição pré-definida""",
    "ptzalarmmask": """Bloqueia movimento PTZ durante alarmes (on/off)""",
    "alarmpresetindex": """Índice da posição pré-definida para alarmes""",
    "poweronpresetindex": """Índice da posição pré-definida ao ligar a câmera""",
    "watchpresetindex": """Índice da posição pré-definida para modo vigilância""",
    "poweronscanenable": """Ativa varredura automática ao ligar (0=desligado, 1=ligado)""",
    "limitleft": """Limite angular esquerdo para movimento (-1=ilimitado ou ângulo)""",
    "limitright": """Limite angular direito para movimento (-1=ilimitado ou ângulo)""",
    "tourinterval": """Intervalos de tempo (s) para tour de presets (ex: 5;10;15)""",
    "imagesize": """Resolução máxima do sensor (ex: '4M169' = 4MP 16:9)""",
    "msize": """Tamanho de snapshot para dispositivos móveis (0=QVGA, 1=VGA, 2=720P)""",
    "model": """Modelo interno do hardware""",
    "hardVersion": """Versão do hardware""",
    "softVersion": """Versão do firmware (contém data compilação -YYYYMMDD)""",
    "webVersion": """Versão da interface web""",
    "rs485Version": """Versão do protocolo RS485""",
    "name": """Nome do dispositivo""",
    "startdate": """Data/hora do último inicialização (YYYY-MM-DD HH:MM:SS)""",
    "upnpstatus": """Status UPnP (on/off)""",
    "facddnsstatus": """Status DDNS do fabricante (on/off)""",
    "th3ddnsstatus": """Status DDNS de terceiros (on/off)""",
    "platformstatus": """Status da plataforma P2P (0=desativado)""",
    "sdshow": """Mostrar status do SD na interface? (0=não, 1=sim)""",
    "sdstatus": """Status do cartão SD (Ready/No Card/Full/Error)""",
    "sdfreespace": """Espaço livre no SD (KB)""",
    "sdtotalspace": """Espaço total do SD (KB)""",
    "name0": """Nome de usuário do administrador""",
    "password0": """Senha do administrador""",
    "authLevel0": """Nível de autorização do administrador (15=máximo)""",
    "show_0": """Visibilidade do OSD região 0 (0=oculto, 1=visível)""",
    "place_0": """Posição do OSD região 0 (0=Topo Esquerdo, 1=Topo Direito, 2=Inferior Esquerdo, 3=Inferior Direito)""",
    "format_0": """Formato de data/hora região 0 (0=YYYY-MM-DD hh:mm:ss, 1=MM/DD/YYYY hh:mm:ss, 2=DD/MM/YYYY hh:mm:ss)""",
    "type_0": """Tipo de conteúdo região 0 (0=data/hora, 1=texto personalizado)""",
    "x_0": """Coordenada X personalizada região 0 (0 a largura máxima)""",
    "y_0": """Coordenada Y personalizada região 0 (0 a altura máxima)""",
    "name_0": """Texto personalizado região 0 (se type_0=1) ou formato de data""",
    "show_1": """Estado da área de cobertura 1: 0=Desativada, 1=Ativada""",
    "place_1": """Posição do OSD região 1 (mesmo código que place_0)""",
    "format_1": """Formato de data/hora região 1 (mesmo que format_0)""",
    "type_1": """Tipo de conteúdo região 1 (0=data/hora, 1=texto personalizado)""",
    "x_1": """Coordenada horizontal do canto superior esquerdo (pixels)""",
    "y_1": """Coordenada vertical do canto superior esquerdo (pixels)""",
    "name_1": """Texto personalizado região 1 (ex: 'Quintal')""",
    "volin_type": """Fonte áudio. Valores: 0=Line-in, 1=Microfone""",
    "volume": """Volume entrada. Limites: 1-100""",
    "aec": """Cancelamento eco. Valores: 0=desligado, 1=ligado""",
    "denoise": """Redução ruído. Valores: 0=desligado, 1=ligado""",
    "ao_volume": """Volume saída. Limites: 1-100""",
    "ip": """Endereço IP. Formato: XXX.XXX.XXX.XXX""",
    "netmask": """Máscara de rede. Formato: XXX.XXX.XXX.XXX""",
    "gateway": """Gateway padrão. Formato: XXX.XXX.XXX.XXX""",
    "dhcpflag": """Modo DHCP. Valores: 'on' (DHCP ativo), 'off' (IP estático)""",
    "dnsstat": """Modo DNS: '1'=Automático, '0'=Manual""",
    "fdnsip": """DNS primário. Formato: XXX.XXX.XXX.XXX (pode ser vazio)""",
    "sdnsip": """DNS secundário. Formato: XXX.XXX.XXX.XXX (pode ser vazio)""",
    "macaddress": """Endereço MAC. Formato: XX:XX:XX:XX:XX:XX""",
    "networktype": """Tipo de conexão. Valores: 'LAN' (cabo), 'WLAN' (wireless)""",
    "rtspport": """Porta RTSP. Valores: 554 ou 1024-49151""",
    "rtpport": """Porta RTP (transporte de mídia). Valores: 1024-65535""",
    "rtmpport": """Porta RTMP. Valores: 1935 ou 1024-49151""",
    "rtsp_aenable": """Autenticação RTSP: '0'=desligada, '1'=ligada""",
    "wf_enable": """Status de habilitação do Wi-Fi: '0'=desligado, '1'=ligado""",
    "wf_ssid": """Nome da rede Wi-Fi (SSID). Comprimento máximo: 63 caracteres""",
    "wf_auth": """Método de autenticação: '0'=Nenhum, '1'=WEP, '2'=WPA-PSK, '3'=WPA2-PSK""",
    "wf_key": """Chave de segurança da rede Wi-Fi. Comprimento: 8-64 caracteres (WPA/WPA2) ou 5/10/13/26 caracteres (WEP)""",
    "wf_enc": """Tipo de criptografia: '0'=TKIP, '1'=AES""",
    "wf_mode": """Modo de operação do Wi-Fi (0=None-Modulated, 1=Modulated, 2=Continuous RX)""",
    "chkres": """Resultado do teste Wi-Fi: '0'=falha na conexão, '1'=sucesso. Disponível ~10s após chkwirelessattr""",
    "interip": """Endereço IP público da conexão de rede (formato XXX.XXX.XXX.XXX)""",
    "our_enable": """Status: '0'=desligado, '1'=ligado""",
    "our_server": """Servidor DDNS (ex: 'hipcam.org')""",
    "our_port": """Porta do servidor (normalmente 80)""",
    "our_uname": """Nome de usuário""",
    "our_passwd": """Senha""",
    "our_domain": """Domínio personalizado (pode ser vazio)""",
    "our_interval": """Intervalo de atualização em segundos (ex: 180 = 3 minutos)""",
    "upm_enable": """Status: '0'=desligado, '1'=ligado""",
    "d3th_enable": """Status: '0'=desligado, '1'=ligado""",
    "d3th_service": """Provedor: 0=Dyndns.org, 1=3322.org, 2=Dynddns.us, 3=No-ip.com""",
    "d3th_uname": """Usuário do serviço""",
    "d3th_passwd": """Senha do serviço""",
    "d3th_domain": """Domínio registrado (ex: 'mydomain.dyndns.org')""",
    "display_mode": """Modo de exibição (0=preto branco, 1=cores)""",
    "brightness": """Brilho da imagem (0–100)""",
    "saturation": """Saturação da cor (0-254)""",
    "sharpness": """Nitidez da imagem (0–100)""",
    "contrast": """Contraste da imagem (0–100)""",
    "hue": """Matiz de cor (0–100)""",
    "wdr": """Wide Dynamic Range (on/off)""",
    "wdrvalue": """Valor do WDR (1–30) — controla o nível de compensação de faixa dinâmica ampla.""",
    "night": """Modo noturno (on/off)""",
    "shutter": """Velocidade do obturador em microssegundos (ex: 2000)""",
    "flash_shutter": """Obturador para flash (valor desconhecido, ex: 14)""",
    "flip": """Rotação vertical da imagem (on=ativado)""",
    "mirror": """Espelhamento horizontal (on=ativado)""",
    "gc": """Ganho de cor (valor ex: 90)""",
    "ae": """Modo de exposição automática (0, 1, 2... depende do modelo)""",
    "targety": """Brilho alvo da exposição (ex: 70)""",
    "noise": """Redução de ruído (0=desativado, outros=nível)""",
    "gamma": """Correção de gama (0=off, 1=on)""",
    "aemode": """Modo de exposição automática (0=central, 1=media ponderada, etc.)""",
    "imgmode": """Modo de imagem (1=padrão, outros desconhecidos)""",
    "saradc_switch_value": """Valor de comutação do sensor de luz para IR-CUT (ex: 800)""",
    "saradc_b2c_switch_value": """Valor de retorno da comutação (BW-Color)""",
    "infraredstat": """Estado do IR (close=desligado, open=ligado)""",
    "lamp_mode_flag": """Modo de controle da lâmpada (0=manual, 1=auto, 2=timer)""",
    "lamp_mode": """Estado da lâmpada (0=desligada, 1=ligada)""",
    "lamp_timeout": """Tempo de desligamento automático em segundos (ex: 30)""",
    "lamp_chktime": """Intervalo de verificação da luz ambiente (em segundos)""",
    "ov_enable": """Habilita/desabilita o serviço ONVIF: 0=Desativado, 1=Ativado""",
    "ov_port": """Porta TCP para comunicação ONVIF (1-65535, padrão 8080)""",
    "ov_authflag": """Exigir autenticação para operações ONVIF: 0=Desligado (acesso aberto), 1=Ligado (usuário/senha obrigatórios)""",
    "ov_forbitset": """Máscara de bloqueio de configurações via ONVIF: Bit 0 (1) = Bloqueia alterações de hora/data, Bit 1 (2) = Bloqueia alterações de vídeo. Valores: 0 (nada bloqueado), 1 (bloqueio tempo), 2 (bloqueio vídeo), 3 (ambos bloqueados)""",
    "ov_subchn": """Canal para streaming secundário ONVIF: 11=Fluxo principal, 12=Subfluxo (normalmente 640x480)""",
    "ov_snapchn": """Canal para captura de snapshots ONVIF: 11=Fluxo principal (alta resolução), 12=Subfluxo (resolução média), 13=Fluxo terciário (baixa resolução)""",
    "ov_nvctype": """Modo de compatibilidade: 0=Implementação padrão ONVIF, 1=Modo compatível com NVRs Uniview (protocolo proprietário)""",
    "videomode": """Modo de operação de vídeo (valor específico do modelo)""",
    "vinorm": """Norma de vídeo (P: PAL, N: NTSC)""",
    "profile": """Perfil do codec (1=Baseline, 3=Main, 4=High, 5=H.265)""",
    "maxchn": """Número máximo de canais de vídeo suportados""",
    "wdrmode": """Wide Dynamic Range (0=desligado, 1=ligado)""",
    "width_1": """Largura do vídeo em pixels (fluxo primário)""",
    "height_1": """Altura do vídeo em pixels (fluxo primário)""",
    "bps_1": """Taxa de bits em kbps (32-8192 para fluxo primário)""",
    "aa_enable": """Habilita alarme de áudio (0=desligado, 1=ligado)""",
    "aa_value": """Sensibilidade do microfone para alarme (0-100)""",
    "snap_chn": """Canal para captura de snapshots durante alarmes""",
    "snap_count": """Número de snapshots por evento de alarme""",
    "snap_name_mode": """Modo de nomeação de snapshots (0=padrão, 1=personalizado)""",
    "snap_alarm_name": """Nome personalizado para snapshots de alarme""",
    "snap_timer_name": """Nome personalizado para snapshots agendados""",
    "cap_cvbs": """Suporte a saída CVBS/vídeo analógico (on/off)""",
    "cap_sd": """Suporte a cartão SD (on/off)""",
    "cap_usb": """Suporte a portas USB (on/off)""",
    "cloud_flag": """Disponibilidade do serviço de nuvem (0=não, 1=sim)""",
    "cloud_enable": """Habilita serviço de nuvem (0=desligado, 1=ligado)""",
    "devtype": """Modelo interno do dispositivo""",
    "io_enable": """Habilita entradas/saídas digitais de alarme (0=desligado, 1=ligado)""",
    "io_flag": """Estado das GPIO (0=NC, 1=NO)""",
    "light_enable": """Controle de LEDs infravermelhos (on/off)""",
    "m1_enable": """Habilita área 1 de detecção de movimento (0/1)""",
    "m1_x": """Coordenada X inicial da área 1 de detecção""",
    "m1_y": """Coordenada Y inicial da área 1 de detecção""",
    "m1_w": """Largura da área 1 de detecção""",
    "m1_h": """Altura da área 1 de detecção""",
    "m1_sensitivity": """Sensibilidade da área 1 (0-100)""",
    "m1_threshold": """Limiar para disparo na área 1 (0-255)""",
    "panrange": """Alcance máximo horizontal do PTZ (graus/passos)""",
    "tiltrange": """Alcance máximo vertical do PTZ (graus/passos)""",
    "panhome": """Posição horizontal 'home' do motor""",
    "tilthome": """Posição vertical 'home' do motor""",
    "pangap": """Folga mecânica horizontal do motor""",
    "tiltgap": """Folga mecânica vertical do motor""",
    "peripheral": """Suporte a visão periférica (0=não, 1=sim)""",
    "selfcheckspeed": """Velocidade do motor durante autoteste""",
    "lenstype": """Tipo de lente (0=fixa, 1=varifocal, etc.)""",
    "trackpreset": """Índice do preset PTZ usado como ponto inicial para rastreamento inteligente""",
    "trackhtimems": """Tempo de resposta horizontal para rastreamento (ms)""",
    "trackvtimems": """Tempo de resposta vertical para rastreamento (ms)""",
    "ntpenable": """Habilita NTP (0/1)""",
    "ntpserver": """Servidor NTP""",
    "ntpinterval": """Frequência de sincronização (horas)""",
    "planrec_enable": """Habilita gravação agendada (0/1)""",
    "planrec_chn": """Canal de vídeo para gravação agendada""",
    "planrec_time": """Duração máxima por gravação (segundos)""",
    "planrec_type": """Tipo de gravação (0=contínua, 1=evento)""",
    "pir_enable": """Habilita sensor PIR (0/1)""",
    "pir_flag": """Estado do sensor PIR (0=inativo, 1=ativo)""",
    "oss_exptime": """Data de expiração do armazenamento online""",
    "oss_totalsize": """Espaço total do armazenamento online (KB)""",
    "oss_usedsize": """Espaço usado no armazenamento online (KB)""",
    "oss_freesize": """Espaço livre no armazenamento online (KB)""",
    "pftype": """Tipo de plataforma P2P (ex: 7=chipset Hisilicon)""",
    "time": """Data e hora atual do dispositivo no formato AAAAMMDDHHMMSS (Ano, Mês, Dia, Hora, Minuto, Segundo)""",
    "as_snap_enable": """Habilita snapshots agendados (0/1)""",
    "as_snap_interval": """Intervalo entre snapshots (segundos)""",
    "as_email_enable": """Habilita envio de email (0/1)""",
    "as_email_interval": """Intervalo de envio por email (segundos)""",
    "as_ftp_enable": """Habilita envio por FTP (0/1)""",
    "as_ftp_interval": """Intervalo de envio por FTP (segundos)""",
    "as_cloud_enable": """Habilita envio para nuvem (0/1)""",
    "as_cloud_interval": """Intervalo de envio para nuvem (segundos)""",
    "at_username0": """Nome de usuário do administrador""",
    "at_password0": """Senha do administrador""",
    "at_authlevel0": """Nível de acesso do administrador (15=máximo)""",
    "xqp2p_enable": """Habilita/desabilita a plataforma XQ-P2P. Valores: 0 (Desligado) ou 1 (Ligado)""",
    "xqp2p_mode": """Modo de operação do protocolo XQ-P2P (não especificado na interface)""",
    "xqp2p_prefix": """Prefixo de identificação do dispositivo no protocolo XQ-P2P""",
    "xqp2p_uid": """Identificador único (UID) do dispositivo na rede XQ-P2P""",
    "xqp2p_pushaddr": """Endereço IP do servidor de push para notificações""",
    "xqp2p_svraddr": """Endereço codificado do servidor principal da plataforma XQ-P2P""",
    "sound_type": """Tipo de som de alarme (0=bip, 1=alarme)""",
    "sound_time": """Duração do som de alarme (segundos)""",
    "smd_type": """Tipo de detecção inteligente (0=padrão, 1=avançado)""",
    "smd_default_gthresh": """Limiar padrão de detecção inteligente""",
    "smd_gthresh": """Limiar configurado de detecção inteligente""",
    "smd_rect": """Exibe retângulos de detecção (0/1)""",
    "smartrack_flag": """Suporte a rastreamento (0/1)""",
    "smartrack_enable": """Habilita rastreamento (0/1)""",
    "smartrack_timeout": """Tempo máximo de rastreamento (segundos)""",
    "ma_server": """Servidor SMTP""",
    "ma_port": """Porta SMTP""",
    "ma_ssl": """Usa SSL/TLS (0/1)""",
    "ma_logintype": """Tipo de autenticação SMTP (0=nenhuma, 1=login)""",
    "ma_username": """Usuário SMTP""",
    "ma_password": """Senha SMTP""",
    "ma_from": """Remetente de emails""",
    "ma_to": """Destinatário de emails""",
    "ma_subject": """Assunto padrão de emails""",
    "ma_text": """Corpo padrão de emails""",
    "ft_server": """Servidor FTP""",
    "ft_port": """Porta FTP""",
    "ft_username": """Usuário FTP""",
    "ft_password": """Senha FTP""",
    "ft_mode": """Modo de conexão FTP: 0=Passivo (recomendado), 1=Ativo (pode exigir ajuste de firewall)""",
    "ft_dirname": """Diretório remoto FTP""",
    "ft_autocreatedir": """Cria diretório automaticamente (0/1)""",
    "stream_num": """Número de streams de vídeo suportados""",
    "smd_enable": """Habilita detecção inteligente (0/1)""",
    "smd_threshold": """Limiar de detecção inteligente (0-255)""",
    "smd_x": """Coordenada X da área de detecção inteligente""",
    "smd_y": """Coordenada Y da área de detecção inteligente""",
    "smd_w": """Largura da área de detecção inteligente""",
    "smd_h": """Altura da área de detecção inteligente""",
    "m2_enable": """Estado da Área 1 de detecção de movimento: 0=Desativada, 1=Ativada""",
    "m2_x": """Posição horizontal do canto superior esquerdo (pixels absolutos, 0=esquerda)""",
    "m2_y": """Posição vertical do canto superior esquerdo (pixels absolutos, 0=topo)""",
    "m2_w": """Largura da área de detecção em pixels (valor inteiro >10)""",
    "m2_h": """Altura da área de detecção em pixels (valor inteiro >10)""",
    "m2_sensitivity": """Sensibilidade ao movimento (1-100): 1=objetos grandes, 100=objetos pequenos""",
    "m2_threshold": """Limiar de mudança de pixels (0-255): Diferença mínima de intensidade para detecção (0=valor padrão)""",
    "m3_enable": """Estado da Área 1 de detecção de movimento: 0=Desativada, 1=Ativada""",
    "m3_x": """Posição horizontal do canto superior esquerdo (pixels absolutos, 0=esquerda)""",
    "m3_y": """Posição vertical do canto superior esquerdo (pixels absolutos, 0=topo)""",
    "m3_w": """Largura da área de detecção em pixels (valor inteiro >10)""",
    "m3_h": """Altura da área de detecção em pixels (valor inteiro >10)""",
    "m3_sensitivity": """Sensibilidade ao movimento (1-100): 1=objetos grandes, 100=objetos pequenos""",
    "m3_threshold": """Limiar de mudança de pixels (0-255): Diferença mínima de intensidade para detecção (0=valor padrão)""",
    "m4_enable": """Estado da Área 1 de detecção de movimento: 0=Desativada, 1=Ativada""",
    "m4_x": """Posição horizontal do canto superior esquerdo (pixels absolutos, 0=esquerda)""",
    "m4_y": """Posição vertical do canto superior esquerdo (pixels absolutos, 0=topo)""",
    "m4_w": """Largura da área de detecção em pixels (valor inteiro >10)""",
    "m4_h": """Altura da área de detecção em pixels (valor inteiro >10)""",
    "m4_sensitivity": """Sensibilidade ao movimento (1-100): 1=objetos grandes, 100=objetos pequenos""",
    "m4_threshold": """Limiar de mudança de pixels (0-255): Diferença mínima de intensidade para detecção (0=valor padrão)""",
    "address": """Endereço do dispositivo PTZ na rede RS-485 (1-255). Cada dispositivo deve ter um endereço único no barramento serial""",
    "baud": """Taxa de transmissão serial (baud rate) para comunicação RS-485. Valores suportados: 1200, 2400, 4800, 9600, 19200, 38400, 57600""",
    "check": """Tipo de verificação de paridade. Valores: 0=None (sem verificação de paridade), 1=Odd (paridade ímpar), 2=Even (paridade par)""",
    "databit": """Número de bits de dados na comunicação serial. Valores suportados: 7 ou 8 bits""",
    "protocal": """Protocolo de comunicação PTZ. Valores: 0=PELCO-D, 1=PELCO-P""",
    "speed": """Velocidade de movimento PTZ (0-60). Controla a velocidade de rotação dos motores pan/tilt. Valores mais altos = movimento mais rápido""",
    "stopbit": """Número de bits de parada na comunicação serial. Valores suportados: 1 ou 2 bits.""",
    "dstmode": """Modo de ajuste para horário de verão (on/off)""",
    "timeZone": """Fuso horário configurado no dispositivo (ex: Europe/Athens, America/Sao_Paulo)""",
    "at_authlevel2": """Nível de acesso de convidado (guest) padrão (1 = privilégios mínimos)""",
    "at_authlevel1": """Nível de acesso do usuário padrão (3 = privilégios moderados)""",
    "at_password1": """Senha do usuário padrão""",
    "at_username1": """Nome do usuário padrão""",
    "at_username2": """Nome do convidado""",
    "at_password2": """Senha de convidado""",
    "wf_speed": """Velocidade máxima de transmissão Wi-Fi em Mbps""",
    "wf_chn": """Canal de frequência Wi-Fi selecionado""",
    "wf_power": """Potência de transmissão do sinal Wi-Fi em dBm""",
    "g4_runmode": """Modo de configuração do APN: 0=Automático (usa APN padrão da operadora), 1=Manual (configuração personalizada)""",
    "g4_simcard": """Estado do cartão SIM: 0=Não detectado, 1=Detectado""",
    "g4_status": """Status de conexão 4G (códigos específicos do fabricante)""",
    "g4_quality": """Qualidade do sinal 4G (0-5, onde 5 é o melhor sinal)""",
    "g4_ver": """Versão do firmware do módulo 4G""",
    "g4_mcc": """Mobile Country Code (código do país da operadora)""",
    "g4_mnc": """Mobile Network Code (código da rede da operadora)""",
    "g4_carrier": """Nome da operadora de rede móvel""",
    "g4_imei": """IMEI (Identificação Internacional de Equipamento Móvel) do dispositivo""",
    "g4_iccid": """Número de identificação do cartão SIM (ICCID)""",
    "g4_apn": """Access Point Name (ponto de acesso para dados móveis)""",
    "g4_username": """Nome de usuário para autenticação no APN""",
    "g4_password": """Senha para autenticação no APN""",
    "g4_authtype": """Tipo de autenticação: 0=Nenhuma, 1=PAP, 2=CHAP, 3=MSCHAP, 4=MSCHAPv2""",
    "op_state": """Estado da conexão com a plataforma: 0=Desconectado, 1=Conectado""",
    "op_enable": """Habilitação da plataforma: 0=Desativado, 1=Ativado""",
    "op_server": """Endereço do servidor da plataforma""",
    "op_port": """Porta de comunicação com a plataforma (padrão 12105)""",
    "op_uname": """Nome de usuário para autenticação na plataforma""",
    "op_passwd": """Senha para autenticação na plataforma""",
    "op_timeout": """Tempo limite de conexão em segundos (1-600)""",
    "gb_enable": """Habilitação do protocolo GB/T 28181: 0=Desativado, 1=Ativado""",
    "gb_svrid": """ID do servidor SIP (SIP Server ID)""",
    "gb_svrip": """Endereço IP do servidor SIP""",
    "gb_svrport": """Porta do servidor SIP (1-65535, padrão 5060)""",
    "gb_devid": """ID do dispositivo (câmera) no sistema GB/T 28181""",
    "gb_devport": """Porta SIP do dispositivo (1-65535, padrão 5060)""",
    "gb_devpwd": """Senha de autenticação do dispositivo""",
    "gb_alarmid": """ID para envio de alarmes (Alarm ID)""",
    "gb_heartcycle": """Intervalo de batimentos cardíacos em segundos (1-65535)""",
    "gb_heartcount": """Número máximo de falhas de batimento cardíaco antes de considerar offline (1-65535)""",
    "gb_regtime": """Tempo de validade do registro em segundos (1-65535)""",
    "gb_macaddr": """Endereço MAC físico da câmera""",
    "d_host": """Array de endereços IP/hostnames dos dispositivos configurados (8 posições)""",
    "d_alias": """Array de nomes amigáveis atribuídos aos dispositivos""",
    "d_port": """Array de portas HTTP para acesso (padrão 80)""",
    "d_username": """Array de usuários para autenticação""",
    "d_password": """Array de senhas para autenticação""",
    "color_1": """Cor da máscara em hexadecimal (RRGGBB) - ex: 000000=preto""",
    "w_1": """Largura da área de cobertura (pixels)""",
    "h_1": """Altura da área de cobertura (pixels)""",
    "show_2": """Estado da área de cobertura 2""",
    "color_2": """Cor da máscara 2""",
    "x_2": """Posição X área 2""",
    "y_2": """Posição Y área 2""",
    "w_2": """Largura área 2""",
    "h_2": """Altura área 2""",
    "show_3": """Estado da área de cobertura 3""",
    "color_3": """Cor da máscara 3""",
    "x_3": """Posição X área 3""",
    "y_3": """Posição Y área 3""",
    "w_3": """Largura área 3""",
    "h_3": """Altura área 3""",
    "show_4": """Estado da área de cobertura 4""",
    "color_4": """Cor da máscara 4""",
    "x_4": """Posição X área 4""",
    "y_4": """Posição Y área 4""",
    "w_4": """Largura área 4""",
    "h_4": """Altura área 4""",
    "tmall_flag": """Indica suporte nativo ao Tmall Genie: 1=Compatível, 0=Não compatível""",
    "tmall_enable": """Controla o estado da integração: 0=Desativado, 1=Ativado""",
    "amazon_flag": """Indica suporte nativo ao Amazon Alexa: 1=Compatível, 0=Não compatível""",
    "amazon_enable": """Controla o estado da integração: 0=Desativado, 1=Ativado""",
    "enable": """Habilita/desabilita a plataforma P2P. Valores: 0 (Desligado) ou 1 (Ligado)""",
    "devid": """ID único do dispositivo (PUID) para identificação na rede P2P""",
    "jport": """Porta do servidor de acesso. Limites: 1-65535""",
    "jserver": """Endereço do servidor de acesso (formato IP ou domínio)""",
    "zport": """Porta do servidor de encaminhamento. Limites: 1-65535""",
    "zserver": """Endereço do servidor de encaminhamento (formato IP ou domínio)""",
    "jinterval": """Intervalo de envio de informações GPS. Unidade: milissegundos. Mínimo: 1000""",
    "p2p_enable": """Habilita/desabilita a funcionalidade P2P. Valores: 0 (Desligado) ou 1 (Ligado)""",
    "p2p_fullfunc": """Indica se a funcionalidade completa do P2P está disponível. Valores: 0 ou 1""",
    "p2p_uid": """Identificador único (UID) do dispositivo na rede P2P""",
    "p2p_server1": """Endereço do servidor P2P primário""",
    "p2p_server2": """Endereço do servidor P2P secundário 1""",
    "p2p_server3": """Endereço do servidor P2P secundário 2""",
    "p2p_server4": """Endereço do servidor P2P secundário 3""",
    "dana_enable": """Habilita/desabilita a plataforma Dana. Valores: 0 (Desligado) ou 1 (Ligado)""",
    "dana_server": """Endereço do servidor da plataforma Dana""",
    "dana_port": """Porta de comunicação com o servidor Dana. Valor padrão: 80""",
    "dana_sn": """Número de série (Serial Number) do dispositivo na plataforma Dana""",
    "hip2p_enable": """Habilita/desabilita a plataforma Hi-P2P. Valores: 0 (Desligado) ou 1 (Ligado)""",
    "hip2p_mode": """Modo de operação do protocolo Hi-P2P (não especificado na interface)""",
    "hip2p_prefix": """Prefixo de identificação do dispositivo no protocolo Hi-P2P""",
    "hip2p_uid": """Identificador único (UID) do dispositivo na rede Hi-P2P""",
    "hip2p_pushaddr": """Endereço do servidor de push para notificações""",
    "hip2p_svraddr": """Endereço do servidor principal da plataforma Hi-P2P""",
    "ldc_enable": """Habilita/desabilita a correção de distorção de lente. Valores: 0 (Desativado) ou 1 (Ativado)""",
    "ldc_xoffset": """Deslocamento horizontal da imagem. Valor inteiro (positivo ou negativo)""",
    "ldc_yoffset": """Deslocamento vertical da imagem. Valor inteiro (positivo ou negativo)""",
    "ldc_ratio": """Intensidade da correção de distorção. Limites: 0-511 (0 = mínima correção, 511 = máxima correção)""",
    "obj_enable": """Habilita/desabilita a plataforma OBJ. Valores: 0 (Desligado) ou 1 (Ligado)""",
    "obj_uid": """Identificador único (UID) do dispositivo na plataforma OBJ (somente leitura)""",
    "waccess_points": """Número total de pontos de acesso Wi-Fi detectados""",
    "wchannel": """Array contendo os canais de operação de cada rede detectada""",
    "wrssi": """Array contendo a intensidade do sinal de cada rede (RSSI em porcentagem)""",
    "wessid": """Array contendo os nomes (SSID) das redes detectadas""",
    "wenc": """Array contendo os tipos de criptografia das redes (ex: AES, TKIP)""",
    "wauth": """Array contendo os métodos de autenticação das redes (ex: WPA2-PSK, WEP)""",
    "wnet": """Array contendo os modos de operação das redes (Infra = infraestrutura, Adhoc = ponto a ponto)""",
    "sr_enable": """Habilita/desabilita o reinício programado. Valores: 0 (Desligado) ou 1 (Ligado)""",
    "sr_day": """Dia da semana para o reinício. Valores: 0-6 (Domingo-Sábado), 7 (todos os dias)""",
    "sr_hour": """Hora específica do reinício (formato 24h). Valores: 0-23""",
    "sr_clock": """⚠️ Parâmetro não utilizado - provavelmente um artefato de implementação antiga""",
    "fisheye_flag": """Habilita/desabilita a correção de distorção fisheye. Valores: 0 (Desativado) ou 1 (Ativado)""",
    "fisheye_mode": """Modo de correção aplicado. Valores: 0 (Padrão), 1 (180°), 2 (360°), etc. (depende do modelo)""",
    "fisheye_lens": """Tipo de lente fisheye. Valores: 0 (Padrão), 1 (Grande angular), 2 (Olho de peixe completo), etc.""",
    "fisheye_xcircle": """Coordenada X do centro da imagem circular (em porcentagem ou pixels)""",
    "fisheye_ycircle": """Coordenada Y do centro da imagem circular (em porcentagem ou pixels)""",
    "fisheye_rcircle": """Raio da imagem circular (em porcentagem ou pixels)""",
    "lampstat": """Estado da iluminação artificial.""",
    "httpsport": """Porta HTTPS""",
    "as_server": """Endereço IP ou domínio do servidor central de alarmes""",
    "as_port": """Porta TCP para comunicação com o servidor""",
    "as_username": """Credencial de autenticação para o servidor""",
    "as_password": """Senha para autenticação no servidor""",
    "as_info": """Campo para informações adicionais/metadados""",
    "goolink_enable": """Serviço Goolink ativo 0-não 1-sim""",
    "goolink_uid": """Device GID (Global ID) - Unique device identifier for P2P connections""",
    "as_enable": """Hablita para tirar uma foto com temporização, enviar para o email.""",
    "as_interval": """Intrevalo em segundos entre fotos""",
    "as_type": """Máscara de ações: 1=salva local (SD), 4=envia email, 5=ambos (1+4)""",
}
